version: '2'

volumes:
  postgres_data_local: {}
  postgres_backup_local: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
      - mailhog
    env_file: .local_env
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=django_playground
      - USE_DOCKER=yes
    ports:
      - "8000:8000"
    command: /start.sh
    restart: unless-stopped

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - postgres_backup_local:/backups
    environment:
      - POSTGRES_USER=django_playground
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    links:
      - postgres:postgres
    image: fenglc/pgadmin4
    volumes:
       - ./pgadmin_data:/root/.pgadmin
    ports:
      - "5050:5050"
   # networks:
   #   - postgres
    restart: unless-stopped

  redis:
      build:
        context: .
        dockerfile: ./compose/production/redis/Dockerfile
      ports:
        - "6379:6379"
      restart: unless-stopped

  localtunnel:
    image: efrecon/localtunnel
    links:
      - django
    command:
      --subdomain ${subdomain} --local-host django --port 8000
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"
    restart: unless-stopped
  celeryworker:
    # https://github.com/docker/compose/issues/3220
    <<: *django
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker.sh

  celerybeat:
    # https://github.com/docker/compose/issues/3220
    <<: *django
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat.sh
