# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-11 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moves_access_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Moves API Access Token of User'),
        ),
    ]
