# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-12 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_moves_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moves_refresh_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Moves API Refresh Token of User'),
        ),
    ]
