# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-18 07:09
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180118_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprofile',
            name='auth_data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
