# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-28 14:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180121_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='websocket',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
