# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-18 07:10
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180118_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dataprofile',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
