# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-14 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_moves_refresh_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovesProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='moves_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('moves_access_token', models.CharField(blank=True, max_length=255, verbose_name='Moves API Access Token of User')),
                ('moves_refresh_token', models.CharField(blank=True, max_length=255, verbose_name='Moves API Refresh Token of User')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='moves_access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='moves_refresh_token',
        ),
    ]
