# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-14 13:24
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180114_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='movesprofile',
            name='data',
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
