# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-16 06:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_movesprofile_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovesHistoryDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, editable=False, verbose_name='Date for the History Data')),
                ('data', jsonfield.fields.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovesHistorySegment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(editable=False, max_length=255, verbose_name='Type of Segment')),
                ('start', models.DateTimeField(default=datetime.date.today, editable=False, verbose_name='Start of Segment')),
                ('end', models.DateTimeField(default=datetime.date.today, editable=False, verbose_name='End of Segment')),
                ('last_update', models.DateTimeField(default=datetime.date.today, editable=False, verbose_name='Last Update to Segment')),
                ('data', jsonfield.fields.JSONField(default=list)),
                ('moves_history_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MovesHistoryDate')),
            ],
        ),
        migrations.CreateModel(
            name='MovesHistorySegmentActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(editable=False, max_length=255, verbose_name='Type of Activity')),
                ('group', models.CharField(editable=False, max_length=255, verbose_name='Group of Activity')),
                ('duration', models.IntegerField(editable=False, verbose_name='Duration of Activity')),
                ('distance', models.IntegerField(editable=False, verbose_name='Distance traveled')),
                ('steps', models.IntegerField(editable=False, verbose_name='Steps taken')),
                ('calories', models.IntegerField(editable=False, verbose_name='Calories burned')),
                ('start', models.DateTimeField(default=datetime.date.today, editable=False, verbose_name='Start of Activity')),
                ('end', models.DateTimeField(default=datetime.date.today, editable=False, verbose_name='End of Activity')),
                ('trackpoints', jsonfield.fields.JSONField(default=list, verbose_name='LatLong Trackpoints')),
                ('moves_history_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.MovesHistorySegment')),
            ],
        ),
    ]
