# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-16 06:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_moveshistorydate_moveshistorysegment_moveshistorysegmentactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveshistorydate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moveshistorysegment',
            name='moves_history_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves_profile', to='users.MovesHistoryDate'),
        ),
    ]
