# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-16 06:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180116_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveshistorydate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves_history_dates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moveshistorysegment',
            name='moves_history_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves_history_segments', to='users.MovesHistoryDate'),
        ),
        migrations.AlterField(
            model_name='moveshistorysegmentactivity',
            name='moves_history_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves_history_activities', to='users.MovesHistorySegment'),
        ),
    ]
